name: CICD Application Deployment Pipeline
run-name: CICD App Deploy invoked for ${{ inputs.repository }}

on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      release:
        required: true
        type: string
      tf_vars:
        required: true
        type: string
      helm_values:
        required: true
        type: string
      env_name:
        required: true
        type: string
#     outputs:
#       pow-result:
#         description: "The value of 2 to the power of pow-value"
#         value: ${{ jobs.calc_pow.outputs.result }}

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Print workflow metadata
        run: |
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
          echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          echo "Run deploy for ${{ inputs.repository }} @ ${{ inputs.release }}"
          echo "Using TFVars file ${{ inputs.tf_vars }}"
          echo "using Helm values file ${{ inputs.helm_values }}"
          echo "For the ${{ inputs.env_name }} environment"

      - name: Display the github object
        run: |
          echo GitHub event object is...
          cat <<EOF
          ${{ toJSON(github) }}
          EOF

      - name: Check out environment repository code
        uses: actions/checkout@v5
        with:
          path: "environment"

      - name: Check out repository code
        uses: actions/checkout@v5
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.release }}
          path: "application"

      - name: List directory contents
        run: |
          pwd
          tree
      - name: List the environment
        run: env

      - run: echo "🍏 This job's status is ${{ job.status }}."
